### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by vanous** [paulfab/touchtyping#1]
Hi there, thank you for your work :)

I would like to extend this to contain Czech words and host the repo on Codeberg (https://codeberg.org/vanous). This will all be (of course) opensourced  and hosted on my Codeberg pages (https://vanous.codeberg.page/). I will (of course) credit you as the original author, but would like to make sure to add proper license. Could you please add a license to this repo?

Thank you

**Comment by paulfab** [comment]
Hello,
You can take anything you want, you don't even need to credit me. This one is great https://en.wikipedia.org/wiki/WTFPL
Enjoy :)

**Comment by vanous** [comment]
Thank you! :)
